### ISSUE TITLE
runing from window7 is not simple

### ISSUE THREAD

**Issue by bkdwei** [barry-scott/scm-workbench#10]
* after git clone the source，I run wb-scm.cmd,it raise error "Error: BUILDER_TOP_DIR is not set".

- after "set  BUILDER_TOP_DIR=F:\python\git\scm-workbench\",I run wb-scm.cmd,it raise error "can not find F:\python\git\scm-workbench\Source\Scm\wb_scm_version.py".
- after rename Source\Scm\make_wb_scm_images.py to Source\Scm\wb_scm_images.py,I run wb-scm.cmd,it raise error "F:\python\git\scm-workbench\Source\Scm\wb_scm_images.py".
- I try to run "python3 wb_scm_main.py",it raise error "ModuleNotFoundError: No module named 'wb_main'".I can not find wb_main.py int the Scm directory.

finally ,i have to down the exe file to run scm-workbench.
http://scm-workbench.barrys-emacs.org/kits/SCM-Workbench-0.9.0-setup.exe

**Comment by barry-scott** [comment]
I use https://github.com/barry-scott/builder.git builder_init.cmd to set BUILDER_TOP_DIR
and run Builder/builder_custom_init.cmd

Then if you run Sources\Scm\wb-scm.cmd it will run nmake to build the other python files
and start scm-workbench.

If you do not have visual studio available you will need to run the command that are in the windows.mak files.

**Comment by barry-scott** [comment]
I have make a number of changes that should make running wb-scm.cmd simpler.

The README.txt has been updated with up to date information.

The Windows scripts no longer depend on nmake and Microsoft Visual Studio.
wb-scm.cmd will run all required scripts if it detects this has not been done.

Please re-open if I need to do more.

**Comment by bkdwei** [comment]
thank you for your update.
