### ISSUE TITLE
WB expects libssl in system installed PySVN

### ISSUE THREAD

**Issue by fiee** [barry-scott/scm-workbench#11]
SCM Workbench 0.9.3

```
Subversion (svn) is not available - dlopen(/Applications/SCM Workbench.app/Contents/Resources/lib/python3.7/lib-dynload/pysvn/_pysvn_3_7.so, 2): Library not loaded: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysvn/libssl.1.0.0.dylib
  Referenced from: /Applications/SCM Workbench.app/Contents/Frameworks/libserf-1.dylib
  Reason: image not found
```

On my Mac (Mojave), I installed Python only via MacPorts, so there’s no `/Library/Frameworks/Python.framework/` at all, and I don’t know why SCM Workbench should look for a libssl in an installed version of PySVN anyway. Shouldn’t it be self-contained?

I can try to compile SCM Workbench on MacPorts Python, if that helps.

**Comment by barry-scott** [comment]
macOS likes its .dylib files to have absolute paths to deps to make them work reliably.
What this means is that when the files are moved to a new folder they do keep looking
in the absolute locations for dependencies.

You can change where .dylib deps are looked for using the install_name_tool.
You can see the deps using otool -L.

$ otool -L /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysvn/_pysvn_3_7.so

**Comment by barry-scott** [comment]
Does Mac Ports have pysvn? Otherwise building pysvn in the MacPorts world
would be one way forwards.

Stepping back what is your goal?

If you want to work on SCM workbench then why not install python from python.org?
If you just want to run SCM workbench why not use the kits I produce?
If you want to use git, hg etc from MacPorts you can configure that if Preferences.

**Comment by fiee** [comment]
Yes, MacPorts has PySVN (currently 1.9.6_1).

The only Python framework on my Mac is 2.7 in /System/Library...

I don’t see the need for several installations of Python; since some apps that I installed via MacPorts need Python 3.x anyway, why shouldn’t I use this as default? The python.org distribution can’t install security patches on its own.

My goal is running SVN Workbench anyhow.
This ticket *is* about your precompiled kit. Seems like it contains some paths to libraries on your machine.
Yes, I can configure git and hg from MacPorts, but several functions depend on pysvn, and if I wouldn’t need also svn, I wouldn’t have found SCM workbench...

**Comment by fiee** [comment]
I’m closing this issue, since SCM Workbench 0.9.4 with PySVN 1.9.12 works on OSX 10.14 with python.org 3.8
