### ISSUE TITLE
run script fails

### ISSUE THREAD

**Issue by fiee** [barry-scott/scm-workbench#12]
Trying to run from source (current git checkout) on Linux; necessary steps after installing dependencies:

- cd scm-workbench/Source/Scm
- chmod a+x *.sh *.py
- export PATH=$PATH:../Common
- chmod a+x ../Common/*.py

Failing at:
`u make_wb_scm_version.py` (unknown command u)

Finally failing with:
`ModuleNotFoundError: No module named 'wb_scm_version'`

Your script apparently tries to run several python scripts directly, without path or without changing directories.

**Comment by barry-scott** [comment]
The step you are missing is to run Builder/builder_custom_init.sh first.

$ cd <top level scm workbench folder> 
$ export BUILDER_TOP_DIR=$(pwd)
$ . Builder/builder_custom_init.sh

That sets some env var need to build scm workjbench.

I need to add that to a read me.
There are some docs in Source/Scm/README.txt

I do not need to do any chmod commands, not sure why you did them.

To build SCM workbench as an app in a .dmg do this:

$ cd Kits/macOS
$ ./build-macos.sh

use this to build and start the install (open the dmg file)

$ cd Kits/macOS
$ ./build-macos.sh --install

**Comment by fiee** [comment]
Thank you for the hints. Yes, it would be nice if the READMEs would contain all the essential information.

build-macos.sh is missing "colour-print", but that doesn’t seem to be important.

This is the end of the script’s output:
```
locate /opt/local/Library/Frameworks/Python.framework/Versions/3.7/Python None -> /opt/local/Library/Frameworks/Python.framework/Versions/3.7/Python
checking for any import problems
Modules not found (unconditional imports):
 * ConfigParser (git.config)
 * UserDict (pysvn, pytz.lazy)
 * UserDict.DictMixin (pysvn)
 * _gdbm (dbm.gnu)
 * com (com.sun.jna)
 * com.jna (com.sun)
 * com.sun (com.sun.jna.platform)
 * gitdb_speedups (gitdb.fun, gitdb.pack, gitdb.stream)
 * gitdb_speedups._perf (gitdb.pack, gitdb.stream)
 * gitdb_speedups._perf.PackIndexFile_sha_to_index (gitdb.fun, gitdb.stream)
 * gitdb_speedups._perf.apply_delta (gitdb.fun, gitdb.pack)
 * gitdb_speedups.connect_deltas (gitdb_speedups._perf)
 * itertools.izip (pickle)
 * ordereddict (pkg_resources._vendor.pyparsing)
 * sets (pytz.tzinfo)
 * sip (PyQt5, wb_scm_main_window)
 * win32com (win32com)
 * win32com.shell (win32com.shell)
 * win32com.shellcon (win32com.shell)

Modules not found (conditional imports):
 * com (pkg_resources._vendor.appdirs)
 * com.sun.jna (pkg_resources._vendor.appdirs)
 * com.sun.jna.platform (pkg_resources._vendor.appdirs)
 * sha (gitdb.util)
 * wb_p4_factory (wb_scm_factories)
 * win32com (pkg_resources._vendor.appdirs)
 * win32com.shell (pkg_resources._vendor.appdirs)

Done!
cp: /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pysvn/*.dylib: No such file or directory
Info: build-dmg.sh - start
Info: copy app
Info: Create DMG
./build-dmg.sh: line 31: /Library/Frameworks/Python.framework/Versions/2.7/bin/dmgbuild: No such file or directory
```

I checked a few of the "missing" modules and they are definitely there. I also don’t understand why I should need win32com on a Mac.

The app from dmg.tmp doesn’t start.

`app.tmp/SCM WOrkbench-Devel.app` does start and says:
```
Cannot find .../scm-workbench/Kit/macOS/app.tmp/SCM Workbench-Devel.app/Contents/Resources/scm-workbench-git-callback
```
Don’t know it that’s important.
The app seems to work so far, can’t check further at the moment.

**Comment by fiee** [comment]
If you’d like to check my MacPorts-build version:

[Download from my server](https://sedna.fiee.net/f/8ef2735d85f34d0bb513/?dl=1)

**Comment by barry-scott** [comment]
Can you let me know what changes you made to the scm-workbench code to support your build aginst macports?

I'd like to merge them into the scm-workbench.

**Comment by fiee** [comment]
I only had to change the path of dmgbuild (it’s `/opt/local/Library/Frameworks/Python.framework/Versions/2.7/bin/dmgbuild`).

Of course, when I wrote I had no Python frameworks besides the one in `/System/Library` I forgot those of MacPorts in `/opt/local/Library`.

I didn’t log which ports I had to install, besides ``py37-pysvn`` and ``py27-dmgbuild``, but it was quite easy. I already had a whole bunch installed, including the GUI.

**Comment by fiee** [comment]
Funny/not funny at all: The dmgbuild ports disappeared from MacPorts. The project is still actively maintained, though, the author also fixed a few Python 3 related things recently.

I just updated MacPorts – previous state of my repository was only a few weeks old, and there were dmgbuild ports for all(?) the Python versions.

**Comment by fiee** [comment]
I tried running from source again:

```
cd ~/workspace/scm-borkbench
export BUILDER_TOP_DIR=$(pwd)
. Builder/builder_custom_init.sh
cd Source/Scm
./wb-scm.sh
```

The end of the output is:
```
/Users/hraban/workspace/scm-workbench/Source/Scm
+ case "$( uname )" in
++ uname
+ echo '#!/usr/bin/python2.7'
+ cat ../Git/wb_git_callback_client_unix.py
+ chmod +x scm-workbench-git-callback
+ unset PROG
+ '[' '' = --gdb ']'
+ case "$( uname )" in
++ uname
+ '[' -e /opt/local/bin/pythonw3.7 ']'
+ PATH=/usr/bin:/bin:/usr/sbin:/sbin
+ /opt/local/bin/python3.7 wb_scm_main.py
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

`echo '#!/usr/bin/python2.7'` looks suspicious and `PATH=/usr/bin:/bin:/usr/sbin:/sbin` probably isn’t enough. Changed that, didn’t help. Also just re-installed PyQt5 to no avail.

**Comment by barry-scott** [comment]
The use of macOS system python is correct. wb_git_callback_client_unix.py is a helper script that
does not use Qt.

qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""

Your Qt build is broken. Qt uses a plugin that is platform/window-system dependent.
In this case it wants the cocoa plugin.

In my venv I see this:
./lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib

**Comment by fiee** [comment]
It’s not broken, since building your app and others works, and the library is also there:

```
$ ll /opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/plugins/platforms/
total 10000
-rwxr-xr-x  1 root  wheel   1,7M 22 Jul 12:14 libqcocoa.dylib*
-rwxr-xr-x  1 root  wheel   940K 22 Jul 12:14 libqminimal.dylib*
-rwxr-xr-x  1 root  wheel   957K 22 Jul 12:14 libqoffscreen.dylib*
-rwxr-xr-x  1 root  wheel   1,3M 22 Jul 12:14 libqwebgl.dylib*
```

**Comment by barry-scott** [comment]
I have seen this error in the past and it was caused by a Qt problem with the Qt  installation.
Make sure that the folder you found the plugins in is the same one that Qt uses.

Have a look in the scm-workbench log file for a line like this:

INFO Qt libraryPaths ['/Applications/SCM Workbench.app/Contents/Resources/lib/python3.7/PyQt5/Qt/plugins']

Check that you have the plugins in the folder listed.

When debugging I use these options to wb-scm.sh so the output is in the terminal window.

./wb-scm.sh --log-stdout --noredirect

**Comment by fiee** [comment]
Thanks for the hint, but the path seems right. Here’s the log output:
```
2019-10-22 23:16:34,526 INFO Environment XPC_FLAGS=0x0
2019-10-22 23:16:34,526 INFO Environment XPC_SERVICE_NAME=0
2019-10-22 23:16:34,526 INFO Environment _=/opt/local/bin/python3.7
2019-10-22 23:16:34,526 INFO Environment __CF_USER_TEXT_ENCODING=0x1F5:0x0:0x3
2019-10-22 23:16:34,526 INFO Environment __PYVENV_LAUNCHER__=/opt/local/bin/python3.7
2019-10-22 23:16:34,526 INFO app_dir /Users/hraban/workspace/scm-workbench/Source/Scm
2019-10-22 23:16:34,526 INFO preferences_dir /Users/hraban/Library/Preferences/org.barrys-emacs.scm-workbench
2019-10-22 23:16:34,527 INFO Qt libraryPaths ['/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyQt5/Qt/plugins']
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

But qt.qpa.plugin doesn’t seem to know about that path (Could not  find ... in **""**).

**Comment by barry-scott** [comment]
At this point you will need the help of people knowledgeable about PyQy and Qt config in your MacPorts environment.

I do use MacPorts for kmymoney, but its a nightmare doing the build and I cannot upgrade to
track what you are doing.

**Comment by fiee** [comment]
I’m closing this issue, since I got a running configuration on OSX 10.14 and there were too many oddities on my side.
