### ISSUE TITLE
Idea: option to use external program as diff tool

### ISSUE THREAD

**Issue by Jorilx** [barry-scott/scm-workbench#16]
Hi and many thanks for SCM workbench!
I was thinking, wouldn't it be nice if there was an option for using an external program as diff tool, instead of the built-in ones? Like the old svn-workbench used to do.

**Comment by barry-scott** [comment]
I see no reason not to do this.
Which OS are you using and which diff tool did you want to use?

**Comment by Jorilx** [comment]
I'm on Linux (Devuan) and I'd like to use [Meld](http://meldmerge.org)

**Comment by barry-scott** [comment]
I made a start on supporting meld in scm workbench.
The code is a first draft and will need work for macOS and Windows.
Its assuming the meld is in /usr/bin/meld and I only changed the git repo diffs.
So svn and hg will still use the none meld diffs.


Are you able to run the version in git?
I'd be interested in your feedback.

What I did is make the tree and file diffs all run meld with a single path argument.

**Comment by Jorilx** [comment]
I'll try it ASAP, many thanks!

**Comment by Jorilx** [comment]
It works, nice! Thanks again :)

I was wondering, could it be even more useful adding a "path to custom diff tool" entry to the preferences, so that any diff tool could be used?

**Comment by barry-scott** [comment]
My thinking is that meld is a greate complient to the workbench features.
I can take advantage of its UI and call its 1 arg, 2 args and 3 args version of the command line based on when the needs are in the workbench code.

For example conflicts would work well with the 3 args verison it seems.

If someone wants another diff tool integrated I can refactor the design and code at that point. Its simpler to just support meld.

**Comment by barry-scott** [comment]
I have updated the meld support to use it in most (may be all) places that diff is required.
meld is called for git, svn and hg.
I have windows, macOS and unix  (fedora, debian, ubuntu) support implemented.
