### ISSUE TITLE
Make some SCM optional

### ISSUE THREAD

**Issue by termim** [barry-scott/scm-workbench#8]
Requiring all SCM interfaces is too much. At least SVN backend could be optional.

**Comment by barry-scott** [comment]
Too much?

Can you expand on what the problem is that you think needs solving please?

On all OS I have tried pysvn, GitPython and hglib-python are available.

The code structure makes adding and removing SCM a simple edit.
Just change the factories.

**Comment by termim** [comment]
The problem is that not everyone has/need/wants install all three supported interfaces.
pysvn for one requires a bunch of SVN related shared libraries and I for example did not
use SVN for more than decade now.
When I tried to run scm-workbench it simply crashed on me with a traceback. It would be much more user friendly to gracefully say something like: "pysvn module has not been found, disabling SVN interface." and continue with git and hg. :)

**Comment by barry-scott** [comment]
I have made the changes to make all the SCM optional if their python dependencies are not met.
This is in 7438dff2c82a13be1cb2e1e05300cca002a8771a.

**Comment by barry-scott** [comment]
Oh and I added a README.txt to describe how to run SCM Workbench from the git sources.
