### ISSUE TITLE
Crashes after every SVN action

### ISSUE THREAD

**Issue by MakoSDV** [barry-scott/scm-workbench#9]
I used pySVN workbench on my old laptop, but now I see we're suggested to use SCM workbench instead.  However, I cannot get it to work properly.

I'm using Windows 10.  I have Python 3.6 and 3.7 installed.

I copied the svn project files from my old laptop and SCM was able to find the project and add it.  However, selecting Update causes SCM Workbench to crash.  I tried to Checkin a change, but that also caused it to crash.  I can browse the project tree and see the status of files and I can do a Cleanup, but that is all I have been able to do successfully.  Any other actions cause SCM Workbench to crash.  Every time it crashes, it puts a lock, so I need to do a cleanup in order to try again.

I can interact with the SVN project in IntelliJ and using the SlikSVN CLI client, so the issue does not seem to be with the SVN server or the local workspace, but with SCM Workbench.

Please let me know what other information I can provide.

**Comment by barry-scott** [comment]
I'll build and upload the latest version of the code in the next day or so.
That should help.

**Comment by barry-scott** [comment]
I have uploaded 0.9.0 release. Please try this out and if you still seeing problems let me know.
